blank_issues_enabled: false
contact_links:
  - name: Documentação
    url: https://github.com/oangelo/Calculo-Vetorial-Exploracao-Espacial/blob/main/CONTRIBUTING.md
    about: Consulte a documentação antes de abrir uma issue
